set nocompatible

" RStudio default code formatting settings for tabs, spaces, and code width
set ts=4
set sw=4
set et
au FileType javascript setlocal shiftwidth=2 tabstop=2
au FileType cpp setlocal shiftwidth=3 tabstop=3
au FileType java setlocal shiftwidth=3 tabstop=3
au FileType r setlocal shiftwidth=2 tabstop=2 et
au FileType ruby setlocal shiftwidth=2 tabstop=2 et
set colorcolumn=100

" don't clutter with Vim backup files
set backupdir=~/.vimbackup
set directory=~/.vimswap

" Other preferences
set nu
set noerrorbells visualbell t_vb=
set wmh=0
set hls
set incsearch
set laststatus=2
set encoding=utf-8
set t_Co=256
set showcmd
let mapleader = ","
set cursorline
set bs=2
set showcmd
set nowrapscan
syntax on

inoremap jk <ESC>
set encoding=utf-8
let g:netrw_browse_split = 3

filetype plugin on

" auto-install vim-plug https://github.com/junegunn/vim-plug/wiki/tips#automatic-installation
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/.vim/plugged')

" Make sure you use single quotes

Plug 'vimwiki/vimwiki'

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
" Plug 'junegunn/vim-easy-align'

" Any valid git URL is allowed
" Plug 'https://github.com/junegunn/vim-github-dashboard.git'

" Multiple Plug commands can be written in a single line using | separators
" Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
" Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
" Plug 'tpope/vim-fireplace', { 'for': 'clojure' }

" Using a non-default branch
" Plug 'rdnetto/YCM-Generator', { 'branch': 'stable' }

" Using a tagged release; wildcard allowed (requires git 1.9.2 or above)
" Plug 'fatih/vim-go', { 'tag': '*' }

" Plugin options
" Plug 'nsf/gocode', { 'tag': 'v.20150303', 'rtp': 'vim' }

" Plugin outside ~/.vim/plugged with post-update hook
" Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }

" Unmanaged plugin (manually installed and updated)
" Plug '~/my-prototype-plugin'

" Initialize plugin system
call plug#end()

" Switch vimwiki to markdown syntax
let g:vimwiki_list = [{'path': '~/vimwiki/',
                      \ 'syntax': 'markdown', 'ext': '.md'}]

