set nocompatible

" RStudio default code formatting settings for tabs, spaces, and code width
set ts=4
set sw=4
set et
au FileType javascript setlocal shiftwidth=2 tabstop=2
au FileType cpp setlocal shiftwidth=3 tabstop=3
au FileType java setlocal shiftwidth=3 tabstop=3
au FileType r setlocal shiftwidth=2 tabstop=2 et
au FileType ruby setlocal shiftwidth=2 tabstop=2 et
set colorcolumn=100

" don't clutter with Vim backup files
set backupdir=~/.vimbackup
set directory=~/.vimswap

" Other preferences
set nu
set noerrorbells visualbell t_vb=
set wmh=0
set hls
set incsearch
set laststatus=2
set encoding=utf-8
set t_Co=256
set showcmd
let mapleader = ","
set cursorline
set bs=2
set showcmd
set nowrapscan
syntax on

" Gary's settings
inoremap jk <ESC>
set encoding=utf-8
let g:netrw_browse_split = 3

