alias cls='clear && tmux clear-history'
#alias jdk8='export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home'
#alias jdk11='export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home'
alias jdk11='export JAVA_HOME=/opt/homebrew/opt/openjdk@11'
alias jdk17='export JAVA_HOME=/opt/homebrew/opt/openjdk@17'
