alias cls='clear && tmux clear-history'
alias jdk8='export JAVA_HOME=/Library/Java/JavaVirtualMachines/zulu-8.jdk/Contents/home'
alias jdk11='export JAVA_HOME=/opt/homebrew/opt/openjdk@11'
alias jdk17='export JAVA_HOME=/opt/homebrew/opt/openjdk@17'
alias jdk21='export JAVA_HOME=/opt/homebrew/opt/openjdk@21'
alias rstudio='/Applications/RStudio.app/Contents/MacOS/RStudio'
